//******************************************************
// Autogenerated code. Do not modify this file manually.
//******************************************************
package cs444.generator.parser;

import java.io.Writer;
import java.util.LinkedList;
import java.util.List;

import cs444.generator.lexer.grammar.JoosGrammar;

public class JoosSyntacticGrammarextends Language {

    private static final JoosGrammar tokenGrammar = new JoosGrammar();
    private static final String startRule = "CompilationUnit";
    private static final List<String> rules = new LinkedList<String>();

    static{
        rules.add("Identifier id");
        rules.add("QualifiedIdentifier Identifier N_dot_Identifier1");
        rules.add("N_dot_Identifier N_dot_Identifier1 dot Identifier");
        rules.add("N_dot_Identifier  ");
        rules.add("Literal IntegerLiteral");
        rules.add("Literal floating_point_literal");
        rules.add("Literal char_literal");
        rules.add("Literal str_literal");
        rules.add("Literal BooleanLiteral");
        rules.add("Literal null");
        rules.add("IntegerLiteral decimal_integer_literal");
        rules.add("BooleanLiteral true");
        rules.add("BooleanLiteral false");
        Error generating Syntactic Grammar because an exception was thrown: class cs444.cfgrulesgenerator.exceptions.BNFParseException. Message: No closing pair for: 'RBRACKET'
