//******************************************************
// Autogenerated code. Do not modify this file manually.
//******************************************************
package cs444.cfgrulesgenerator.lexer;

import java.util.HashMap;
import java.util.Map;
public final class Token {
    public enum Type {
        COMMA,
        LHS,
        DAMPERSAND,
        RPAREN,
        STAR,
        LPAREN,
        DPIPE,
        EQ,
        PIPE,
        END_LINE_COMMENT,
        BECOMES,
        WHITESPACE,
        LE,
        MINUS,
        SEMI,
        GT,
        DOT,
        NE,
        LBRACE,
        SLASH,
        PLUS,
        GE,
        NEWLINE,
        RBRACE,
        RBRACKET,
        AMPERSAND,
        EXCLAMATION,
        NON_TERMINAL,
        PCT,
        LBRACKET,
        TERMINAL,
        LT,
        EOF,
        EPSILON
    }
    public static enum Parse {VALID, SYNTAX_ONLY, IGNORE}
    public static final Map<Type, Parse> typeToParse = new HashMap<Type, Parse>(){{put(Type.COMMA, Parse.VALID); put(Type.LHS, Parse.VALID); put(Type.DAMPERSAND, Parse.VALID); put(Type.RPAREN, Parse.SYNTAX_ONLY); put(Type.STAR, Parse.VALID); put(Type.LPAREN, Parse.SYNTAX_ONLY); put(Type.DPIPE, Parse.VALID); put(Type.EQ, Parse.VALID); put(Type.PIPE, Parse.SYNTAX_ONLY); put(Type.END_LINE_COMMENT, Parse.IGNORE); put(Type.BECOMES, Parse.VALID); put(Type.WHITESPACE, Parse.IGNORE); put(Type.LE, Parse.VALID); put(Type.MINUS, Parse.VALID); put(Type.SEMI, Parse.VALID); put(Type.GT, Parse.VALID); put(Type.DOT, Parse.VALID); put(Type.NE, Parse.VALID); put(Type.LBRACE, Parse.SYNTAX_ONLY); put(Type.SLASH, Parse.VALID); put(Type.PLUS, Parse.VALID); put(Type.GE, Parse.VALID); put(Type.NEWLINE, Parse.VALID); put(Type.RBRACE, Parse.SYNTAX_ONLY); put(Type.RBRACKET, Parse.SYNTAX_ONLY); put(Type.AMPERSAND, Parse.VALID); put(Type.EXCLAMATION, Parse.VALID); put(Type.NON_TERMINAL, Parse.VALID); put(Type.PCT, Parse.VALID); put(Type.LBRACKET, Parse.SYNTAX_ONLY); put(Type.TERMINAL, Parse.VALID); put(Type.LT, Parse.VALID); }};
    public final Type type;
    public final String lexeme;
    public Token(Type type, String lexeme) {
        this.type = type;
        this.lexeme = lexeme;
    }
    @Override
    public String toString() {
        return "<" + type.toString() + ", " + lexeme.trim() + ">";
    }
}
