package cs444.codegen;

import java.io.PrintStream;

import cs444.parser.symbols.ATerminal;
import cs444.parser.symbols.NonTerminal;
import cs444.parser.symbols.ast.AInterfaceOrClassSymbol;
import cs444.parser.symbols.ast.BooleanLiteralSymbol;
import cs444.parser.symbols.ast.ByteLiteralSymbol;
import cs444.parser.symbols.ast.CharacterLiteralSymbol;
import cs444.parser.symbols.ast.DclSymbol;
import cs444.parser.symbols.ast.EmptyStatementSymbol;
import cs444.parser.symbols.ast.FieldAccessSymbol;
import cs444.parser.symbols.ast.IntegerLiteralSymbol;
import cs444.parser.symbols.ast.ListedSymbol;
import cs444.parser.symbols.ast.MethodInvokeSymbol;
import cs444.parser.symbols.ast.MethodOrConstructorSymbol;
import cs444.parser.symbols.ast.NameSymbol;
import cs444.parser.symbols.ast.NullSymbol;
import cs444.parser.symbols.ast.ShortLiteralSymbol;
import cs444.parser.symbols.ast.StringLiteralSymbol;
import cs444.parser.symbols.ast.SuperSymbol;
import cs444.parser.symbols.ast.ThisSymbol;
import cs444.parser.symbols.ast.TypeSymbol;
import cs444.parser.symbols.ast.expressions.AddExprSymbol;
import cs444.parser.symbols.ast.expressions.AndExprSymbol;
import cs444.parser.symbols.ast.expressions.ArrayAccessExprSymbol;
import cs444.parser.symbols.ast.expressions.AssignmentExprSymbol;
import cs444.parser.symbols.ast.expressions.CastExpressionSymbol;
import cs444.parser.symbols.ast.expressions.CreationExpression;
import cs444.parser.symbols.ast.expressions.DivideExprSymbol;
import cs444.parser.symbols.ast.expressions.EAndExprSymbol;
import cs444.parser.symbols.ast.expressions.EOrExprSymbol;
import cs444.parser.symbols.ast.expressions.EqExprSymbol;
import cs444.parser.symbols.ast.expressions.ForExprSymbol;
import cs444.parser.symbols.ast.expressions.IfExprSymbol;
import cs444.parser.symbols.ast.expressions.InstanceOfExprSymbol;
import cs444.parser.symbols.ast.expressions.LeExprSymbol;
import cs444.parser.symbols.ast.expressions.LtExprSymbol;
import cs444.parser.symbols.ast.expressions.MultiplyExprSymbol;
import cs444.parser.symbols.ast.expressions.NeExprSymbol;
import cs444.parser.symbols.ast.expressions.NegOpExprSymbol;
import cs444.parser.symbols.ast.expressions.NotOpExprSymbol;
import cs444.parser.symbols.ast.expressions.OrExprSymbol;
import cs444.parser.symbols.ast.expressions.RemainderExprSymbol;
import cs444.parser.symbols.ast.expressions.ReturnExprSymbol;
import cs444.parser.symbols.ast.expressions.SubtractExprSymbol;
import cs444.parser.symbols.ast.expressions.WhileExprSymbol;

public interface ICodeGenVisitor {
    void visit(final MethodInvokeSymbol invoke);
    void visit(final FieldAccessSymbol field);
    void visit(final AInterfaceOrClassSymbol aInterfaceOrClassSymbol);
    void visit(final MethodOrConstructorSymbol method);
    void visit(final CreationExpression creationExpression);
    void visit(final NonTerminal aNonTerminal);
    void visit(final WhileExprSymbol whileExprSymbol);
    void visit(final ForExprSymbol forExprSymbol);
    void visit(final IfExprSymbol ifExprSymbol);
    void visit(final ReturnExprSymbol retSymbol);
    void visit(final TypeSymbol typeSymbol);
    void visit(final NameSymbol nameSymbol);
    void visit(final ATerminal terminal);
    void visit(final CastExpressionSymbol symbol);
    void visit(final NegOpExprSymbol op);
    void visit(final NotOpExprSymbol op);
    void visit(final MultiplyExprSymbol op);
    void visit(final AssignmentExprSymbol op);
    void visit(final DivideExprSymbol op);
    void visit(final RemainderExprSymbol op);
    void visit(final AddExprSymbol op);
    void visit(final SubtractExprSymbol op);
    void visit(final LtExprSymbol op);
    void visit(final EqExprSymbol op);
    void visit(final NeExprSymbol op);
    void visit(final AndExprSymbol op);
    void visit(final OrExprSymbol op);
    void visit(final EAndExprSymbol op);
    void visit(final EOrExprSymbol op);
    void visit(final LeExprSymbol op);
    void visit(final InstanceOfExprSymbol op);
    void visit(final IntegerLiteralSymbol intLiteral);
    void visit(final NullSymbol nullSymbol);
    void visit(final BooleanLiteralSymbol boolSymbol);
    void visit(final ThisSymbol thisSymbol);
    void visit(final SuperSymbol thisSymbol);
    void visit(final StringLiteralSymbol stringSymbol);
    void visit(final CharacterLiteralSymbol characterSymbol);
    void visit(final EmptyStatementSymbol emptySymbol);
    void visit(final ArrayAccessExprSymbol arrayAccess);
    void visit(final DclSymbol dclSymbol);
    void visit(final ListedSymbol listedSymbol);
    void visit(final ByteLiteralSymbol byteLiteral);
    void visit(final ShortLiteralSymbol shortLiteral);

    void printToFileAndEmpty(PrintStream printer);
}
